# MATM063: Principles of Data Science, Python LAB

Important to note, [Start:Stop:Step] is the format for all matrix operations, if left as blank the start is at the beginning, the stop is at the end and the step is 1.

In [15]:
import scipy as sp
n=4
A = sp.linalg.hilbert(n)
s = A[::1, :]
s

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

## Worksheet 2 (Week 2) Exercises only

#### Question 1: Defining matrices and performing operations

In [7]:
import numpy as np
A = np.array([[1,4,2],[3,5,7],[4,3,2]])
print(np.mean(A[0]))
print(np.mean(A[1])) 
print(np.mean(A[2]))
print(f'One can see that column 2 has the largest mean')

2.3333333333333335
5.0
3.0
One can see that column 2 has the largest mean


Define a four by four matrix A and find its transpose, trace, determinant and inverse.

In [ ]:
A = np.array([[1,2,1,1],[2,2,1,2],[3,3,3,3],[4,9,9,5]])

A_transpose = A.T
A_trace = np.trace(A)
A_determinant = np.linalg.det(A)
A_inverse = np.linalg.inv(A)

print(A_transpose)
print(A_trace)
print(A_determinant)
print(A_inverse)

[[1 2 3 4]
 [2 2 3 9]
 [1 1 3 9]
 [1 2 3 5]]
11
-2.9999999999999996
[[ 4.00000000e+00 -4.00000000e+00  3.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00 -2.36847579e-16 -3.33333333e-01 -5.92118946e-17]
 [-0.00000000e+00 -1.00000000e+00  6.66666667e-01 -0.00000000e+00]
 [-5.00000000e+00  5.00000000e+00 -3.00000000e+00  1.00000000e+00]]


#### Question 2: Solving Matrix-vector systems

In [29]:
from sympy import symbols, Eq, solve

x, y = symbols('x y')

eq1 = Eq(3*x + 4*y, 5) 
eq2 = Eq(-1*x + 2*y, 3) 

solution = solve((eq1, eq2), (x, y))
print(solution)  


{x: -1/5, y: 7/5}


In [30]:
x, y, z = symbols('x y z')

eq1 = Eq(4*x -5*y + 2*z, 7) 
eq2 = Eq(8*x +5*y - 4*z, 10) 
eq3 = Eq(3*x - 2*y + 1*z, 5)

solution = solve((eq1, eq2, eq3), (x, y, z))
print(solution) 

{x: 3/2, y: 0, z: 1/2}


#### Question 3: Pandas: treating NaN and None values

In [33]:
import pandas as pd

df = pd.DataFrame([[np.nan, 2, None, 0],
[3, 4, np.nan, 1],
[None, np.nan, np.nan, np.nan],
[np.nan, 3, np.nan, 4]],
columns=list("ABCD"))

print(df)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0


##### Fill missing values with 0

In [45]:
df.fillna(0)
print(df.fillna(0))
print(df)
#this shows that df itself is not changed by the fillna command, 
#we will omit this moving forward

     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0


##### using the forward and backward method

In [43]:
print(df.ffill())
print(df.bfill())
#note that the filling methods do not change values already defined to be non-zero

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0
     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0


##### filling all missing values per column with the column mean

In [44]:
df.fillna(value=df.mean())

A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

##### replace in df all missing values in columns A,B,C,D with 1,2,3,4 respectively, this time actually modifying df

In [46]:
print(df)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0


In [52]:
df['A'] = df['A'].fillna(1)
df['B'] = df['B'].fillna(2)
df['C'] = df['C'].fillna(3)
df['D'] = df['D'].fillna(4)
print(df, f'Df is now changed')

     A    B    C    D
0  1.0  2.0  3.0  0.0
1  3.0  4.0  3.0  1.0
2  1.0  2.0  3.0  4.0
3  1.0  3.0  3.0  4.0 Df is now changed


#### Question 4: Pandas: working with Series and DataFrames

A fruit shop sells in 1 day on average (in kg) (20 bananas, 35 apples, 11 pears, 5 pineapples) for a price per kilo of (1.9, 3.5, 4.2, 6.7), respectively.

Create to data series named nmb_sold and price_kg and create a data frame where the keys share the names of these data series.

In [71]:
kg_sold = pd.Series({'Bananas': 20, 'Apples': 35, 'Pears': 11, 'Pineapples':5})
price_kg = pd.Series({'Bananas':1.9, 'Apples': 3.5, 'Pears': 4.2, 'Pineapples': 6.7})
data = pd.DataFrame({'kg_sold':kg_sold, 'price_kg':price_kg})
data

kg_sold  price_kg
Bananas          20       1.9
Apples           35       3.5
Pears            11       4.2
Pineapples        5       6.7

Add a column named income that presents the money the shop earned through these sellings for each fruit type.

In [72]:
data['income'] = data['kg_sold'] * data['price_kg']
data

kg_sold  price_kg  income
Bananas          20       1.9    38.0
Apples           35       3.5   122.5
Pears            11       4.2    46.2
Pineapples        5       6.7    33.5

Calculate the total income earned per day by selling fruits and output the following line: The total daily income by selling fruits is ??? Pounds

In [73]:
print(f'The total income perday by selling fruits is', data['income'].sum(), 'pounds.')

The total income perday by selling fruits is 240.2 pounds.


Add another two rows to the table with average sellings of: Tomatos, 15 kg, and Potatos, 28 kg (price per kg: 2.9 and 1.4, respectively). Create
first a new series, then a dataframe, and then add this to the existing dataframe.

In [74]:
kg_sold = pd.Series({'Tomatoes':15, 'Potatoes':28})
price_kg = pd.Series({'Tomatoes':2.9, 'Potatoes':1.4})
data_new = pd.DataFrame({'kg_sold':kg_sold_new, 'price_kg':price_kg_new})
data_new

kg_sold  price_kg
Tomatoes       15       2.9
Potatoes       28       1.4

In [77]:
data_combined = pd.concat([data, data_new])
data_combined
#note that income for newest entries is undefined still

kg_sold  price_kg  income
Bananas          20       1.9    38.0
Apples           35       3.5   122.5
Pears            11       4.2    46.2
Pineapples        5       6.7    33.5
Tomatoes         15       2.9     NaN
Potatoes         28       1.4     NaN

For this extended data frame: determine also here the income per vegetable and recalculate and output the total daily income for selling both fruits
and vegetables.

In [79]:
data_combined['income'] = data_combined['kg_sold'] * data_combined['price_kg']
data_combined

kg_sold  price_kg  income
Bananas          20       1.9    38.0
Apples           35       3.5   122.5
Pears            11       4.2    46.2
Pineapples        5       6.7    33.5
Tomatoes         15       2.9    43.5
Potatoes         28       1.4    39.2

In [80]:
print(f'The new total income perday by selling fruits is', data_combined['income'].sum(), 'pounds.')

The new total income perday by selling fruits is 322.9 pounds.
